NUMPY ARRAYS AND SOME FUNCTIONS

In [74]:
import numpy as np

In [75]:
my_list=[1,2,3]

In [76]:
my_list

[1, 2, 3]

In [77]:
arr=np.array(my_list)

In [78]:
arr

array([1, 2, 3])

In [79]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [80]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [82]:
np.zeros(3)

array([0., 0., 0.])

In [83]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [84]:
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [85]:
np.linspace(0,5,100) #linspace is different from arange
# arange outputs integers from a to b with a defined gap
# whereas linspace divides the interval from a-b into n parts so it can output float values too  

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [86]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [87]:
l1=np.random.rand(5) # 1D array of 5 random didigts from 0-1
l2=np.random.randint(5)# a random integer from 0-5
l3=np.random.randn(10)# 10 random decimel nos (not in any specific interval)
l4=np.random.randint(1,100,10)#10 random integers from 1-100

In [88]:
print(l1,l2)
print(l3)
print(l4)

[0.19030046 0.90167125 0.62509833 0.96885628 0.63456638] 4
[ 0.70038282  0.51236816  1.18202317 -2.09672251 -0.11197684 -1.29703773
 -0.45305153  1.44571344 -0.26986896 -0.38068311]
[39 18 40 71 83 24 69 29  8 80]


In [89]:
arr=np.random.randint(5,50,(5,5))
print(arr)
print(arr.shape)

[[10  5 44 26 17]
 [32 22 11 47  8]
 [19  9 27 39  7]
 [45 34 14 26 29]
 [21 17 23 12 49]]
(5, 5)


In [90]:
arr=arr.reshape(25)
print(arr)
print(arr.shape)


[10  5 44 26 17 32 22 11 47  8 19  9 27 39  7 45 34 14 26 29 21 17 23 12
 49]
(25,)


In [91]:
a=arr.max() #max value
b=arr.min()#min value
c=arr.argmax()#index of max value
d=arr.argmin()#index of mmin vale

print(a,b,c,d)

49 5 24 1


In [92]:
arr.dtype

dtype('int32')

In [93]:
from numpy.random import randint

In [94]:
randint(5,13,5)

array([ 8,  8, 12, 10, 12])

ARRAY INDEXING AND SELECTION

In [119]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [120]:
arr[8]

8

In [121]:
arr[1:5]

array([1, 2, 3, 4])

In [122]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [123]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [124]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [125]:
arr[::3] #From start to end with interval 3

array([0, 3, 6, 9])

In [127]:
x=arr[6]
print(x)
x=100
print(arr)

slice_of_array=arr[:5]
slice_of_array[:]=100 #This not only changes slice_of_array but also the original arr
                      #This shows that slice_of_array is not a copy but just a view 
                      #This is done to avoid avoid memory issues with b=very large arrays
                       
print(slice_of_array)
print(arr)

6
[100 100 100 100 100   5   6   7   8   9  10]
[100 100 100 100 100]
[100 100 100 100 100   5   6   7   8   9  10]


In [128]:
arr_copy=arr.copy()

In [132]:
arr_copy[:]=99

In [133]:
arr_copy 

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [134]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [136]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [140]:
arr_2d[2,2] #We prefer this over the method in next cell

9

In [141]:
arr_2d[2][2]

9

In [143]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [144]:
# Conditional Selection

In [145]:
arr=np.arange(1,100,7)
arr

array([ 1,  8, 15, 22, 29, 36, 43, 50, 57, 64, 71, 78, 85, 92, 99])

In [146]:
arr%2==0

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False])

In [148]:
arr[arr%2==0] #We have selected elements where the condition inside the bracket was true

array([ 8, 22, 36, 50, 64, 78, 92])

NUMPY OPERATIONS


In [149]:
arr=np.arange(19)

In [150]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36])

In [152]:
arr+100 

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118])

In [154]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324])

In [155]:
arr/arr #nan = not a number (its a warning so we'll still get an output)

C:\Users\Sayuj Gupta\AppData\Local\Temp\ipykernel_6420\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.])

In [156]:
1/arr #inf = infinity

C:\Users\Sayuj Gupta\AppData\Local\Temp\ipykernel_6420\2277913049.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr #inf = infinity


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556])